services:
  getting-started:
    image: tongenx/fast-ci-cd:${APP_IMAGE_TAG:-latest}
    ports:
      - "80:3000"
    volumes:
      - /swarm-nodes/db-todo:/etc/todos
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config: 
        parallelism: 0
        delay: 5s

volumes:
  db-todo:
    external: true