#name: CD - cluster Docker Swarm
name: fast-cd

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: "Ambiente de deployment"
                required: true
                options:
                - dev
                - prod
            imageTag:
                required: true
                description: "Deploy imagem tag"
                default: "latest"

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      HOST_ENV: "34.135.241.224"
      SSH_USER: "egr"
      SSH_PORT: 22
      STACK_NAME: todo-app
      STACK_FILE: todo-list.yml
    
    steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - name: Copiar o arquivo para o cluster Swarm
       uses: appleboy/scp-action@v0.1.4
       with:
         host: ${{ env.HOST_ENV }}
         username: ${{ env.SSH_USER }}
         key: ${{ secrets.ANSIBLE_SSH_KEY }} 
         passphrase: ${{ secrets.ANSIBLE_SSH_PASSPHRASE }}
         port: ${{ env.SSH_PORT }}
         source: ${{ env.STACK_FILE }} 
         target: $HOME 

     - name: Deploy no cluster Swarm
       uses: appleboy/ssh-action@v1.0.3
       with:
         host: "${{ env.HOST_ENV }}"
         username: "${{ env.SSH_USER }}"
         key: ${{ secrets.ANSIBLE_SSH_KEY }}
         passphrase: ${{ secrets.ANSIBLE_SSH_PASSPHRASE }}
         port: "${{ env.SSH_PORT }}"
         script: |
           export APP_IMAGE_TAG=${{ github.event.inputs.imageTag }}
           sudo docker stack deploy -c $HOME/${{ env.STACK_FILE }} ${{ env.STACK_NAME }}