#name: CI - cluster Docker Swarm
name: fast-ci

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
     
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tongenx/fast-ci-cd:${{ github.event.number == 0 && 'latest' || format('PR-{0}', github.event.number) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Disparar deployment em dev
        uses: benc-uk/workflow-dispatch@v1
        env:
          IMAGE_TAG: ${{ github.event.number == 0 && 'latest' || format('PR-{0}', github.event.number) }}
        with:
          workflow: cd.yml
          inputs: '{ "environment": "dev", "imageTag": "${{ env.IMAGE_TAG }}" }'
          token: "${{ secrets.TOKEN_GITHUB }}"
          ref: main
  